//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTNN_Win.BIZ
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class KhoaThi
    {
        public KhoaThi()
        {
            this.PhongThis = new HashSet<PhongThi>();
            this.ThiSinhCuaKhoaThis = new HashSet<ThiSinhCuaKhoaThi>();
        }
    
        public int MaKhoaThi { get; set; }
        public string TenKhoaThi { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public string TrangThai { get; set; }
        [Browsable(false)]
        public virtual ICollection<PhongThi> PhongThis { get; set; }
        [Browsable(false)]
        public virtual ICollection<ThiSinhCuaKhoaThi> ThiSinhCuaKhoaThis { get; set; }
    }
}
