//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTNN_Win.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongThi
    {
        public PhongThi()
        {
            this.ThiSinhTheoPhongThis = new HashSet<ThiSinhTheoPhongThi>();
        }
    
        public int MaPhongThi { get; set; }
        public string TenPhongThi { get; set; }
        public string TrinhDo { get; set; }
        public Nullable<int> SoLuongThiSinh { get; set; }
        public Nullable<int> MaKhoaThi { get; set; }
    
        public virtual KhoaThi KhoaThi { get; set; }
        public virtual ICollection<ThiSinhTheoPhongThi> ThiSinhTheoPhongThis { get; set; }
    }
}
