//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTNN_Win.BIZ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_TT_NGOAINGUEntities : DbContext
    {
        public QL_TT_NGOAINGUEntities()
            : base("name=QL_TT_NGOAINGUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KhoaThi> KhoaThis { get; set; }
        public DbSet<PhongThi> PhongThis { get; set; }
        public DbSet<ThiSinh> ThiSinhs { get; set; }
        public DbSet<ThiSinhCuaKhoaThi> ThiSinhCuaKhoaThis { get; set; }
        public DbSet<ThiSinhTheoPhongThi> ThiSinhTheoPhongThis { get; set; }
    }
}
