//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTNN_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongThi()
        {
            this.ThiSinhTheoPhongThis = new HashSet<ThiSinhTheoPhongThi>();
        }
    
        public int MaPhongThi { get; set; }
        public string TenPhongThi { get; set; }
        public string TrinhDo { get; set; }
        public Nullable<int> SoLuongThiSinh { get; set; }
        public Nullable<int> MaKhoaThi { get; set; }
    
        public virtual KhoaThi KhoaThi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThiSinhTheoPhongThi> ThiSinhTheoPhongThis { get; set; }
    }
}
