//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTNN_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThiSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThiSinh()
        {
            this.ThiSinhCuaKhoaThis = new HashSet<ThiSinhCuaKhoaThi>();
            this.ThiSinhTheoPhongThis = new HashSet<ThiSinhTheoPhongThi>();
        }
    
        public int MaThiSinh { get; set; }
        public string TenThiSinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string Cmnd { get; set; }
        public string SoDienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThiSinhCuaKhoaThi> ThiSinhCuaKhoaThis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThiSinhTheoPhongThi> ThiSinhTheoPhongThis { get; set; }
    }
}
